name: xdoc
banner: true

#xdoc:
#  dir: /docs

web:
  entries:
  - address: :8000

log:
  loggers:
  - level: info
    writers: console
  writers:
  - name: console
    type: console
    layout: '[{L}]{T}: {M}{N}'